AllCops:
  Exclude:
    # This code was taken from the backports gem. We don't want to mess with it.
    - spec/spec_helper.rb
    - Gemfile
Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 100
